### ISSUE TITLE
hardcoded to create war in production mode. Grails offers command line params for different environments. Would be nice to have user specified opt for instances used as test/staging

### ISSUE THREAD

**Issue by nvaidyan** [heroku/heroku-buildpack-grails#21]
Problem is in compile:

COMPILECMD="grails -Divy.default.ivy.user.dir=$CACHE_DIR compile --non-interactive"
echo "-----> Executing $COMPILECMD"
eval "$COMPILECMD" | sed -u 's/^/       /'
check_build_status

BUILDCMD="grails $BUILDCMD_OPT -Divy.default.ivy.user.dir=$CACHE_DIR war --non-interactive"
echo "-----> Executing $BUILDCMD"
eval "$BUILDCMD" | sed -u 's/^/       /'
check_build_status

Documentation on grails war is here http://grails.org/doc/latest/guide/conf.html#environments

Ideally $BUILDCMD_OPT could take on more values than --plain-output. This would require the build pack to either be able to take in parameters or work with the grails community (perhaps with Bert Beckwith's heroku plugin) to determine a convention based location where such parameters could be stored in the application source itself, that the script could read from.

**Comment by jkutner** [comment]
fixed by #39
