### ISSUE TITLE
Update webapp-runner to version 7.0.40.1 to support UTF-8 URI Encoding 

### ISSUE THREAD

**Issue by sspotorno** [heroku/heroku-buildpack-grails#40]
Hi!

I am having an issue with URI encoding when query parameters are sent to the server with special characters in Spanish that are written with accent marks such as á, é, í, ó, ú. 

To solve this problem in Tomcat you have to define the URIEncoding attribute in the connector as UTF-8. 

```xml
<Connector port='8080' protocol='HTTP/1.1' connectionTimeout='20000'
           redirectPort='8443' URIEncoding='UTF-8' />
```
With webapp-runner (in newer versions) there is an argument that could be sent so as to specified the URI Encoding, which is:

```
--uri-encoding  utf-8
```
This could be easily configured in RUNNER_OPTS Config Variables from a Heroku App. But with the version that is configured now in the buildpack, we do not have this option.

Could it be possible to upgrade the webapp-runner version to 7.0.40.1?

Thanks!
Sebastian

**Comment by jkutner** [comment]
I've updated the master branch with webapp-runner 7.0.57.2. We'll probably release the buildpack today or tomorrow, but in the meantime you use it by running:

    $ heroku buildpack:set https://github.com/heroku/heroku-buildpack-grails.git

Thanks!
