### ISSUE TITLE
How can I change grails environment during compilation?

### ISSUE THREAD

**Issue by sspotorno** [heroku/heroku-buildpack-grails#42]
Hi! 

Is there a way to set the grails environment during compile script? I am trying to use an environment different from production but i am not able to do it. I tried with GRAILS_ENV config variable but that does not work it will always compile with production environment. Do you know if there is something else i should do?

Thanks!

**Comment by jkutner** [comment]
Fixed by b1214c577a8b9e806f38560a34adf2b23f13833b new buildpack should be released soon, but you can use the latest by running `heroku buildpacks:set https://github.com/heroku/heroku-buildpack-grails.git`

thanks for reporting this!
