### ISSUE TITLE
--expand-war

### ISSUE THREAD

**Issue by rhart** [heroku/heroku-buildpack-grails#43]
I have an old Grails app runining on Heroku and trying to deploy recently gives me an error of `ERROR: Context 'file:/app/--expand-war' does not exist`.  

The command that's being run is `Starting process with command "java -Xmx384m -Xss512k -XX:+UseCompressedOops -jar server/jetty-runner.jar --expand-war $RUNNER_OPTS --port 17783 --uri-encoding UTF-8 target/*.war"` and I think it's the `--expand-war` causing the problems, this wasn't there in previous working commands.  Any idea what might be going wrong?

**Comment by jkutner** [comment]
It looks like the buildpack thinks you are running with webapp-runner, but your cache has jetty-runner. This is probably due to a very old version of the buildpack that set your app this way, and now things are different.

I think the solution is to create a `system.properties` file and put the following in it:

```
grails.application.container=jetty
```

Please give that a try. Thanks

**Comment by rhart** [comment]
Tried that already and it didnt work.  In the application root folder right?  Will try again to double check.

**Comment by jkutner** [comment]
Did you commit that file to Git?

**Comment by rhart** [comment]
Just tried again.  Defo committed and the result is the same :(

**Comment by jkutner** [comment]
I think your next best bet is to purge your cache. But before doing this, it might be good to test with a fresh app. That is, create a new app with `heroku create` and `git push heroku master` to that app. See if you get the same problem or not.

If that clears things up, you can just keep the new app. Or you can purge the cache of your existing app with the [heroku-repo plugin](https://github.com/heroku/heroku-repo).

**Comment by rhart** [comment]
Great idea, thanks.

**Comment by rhart** [comment]
This is resolved now, I set it to use the legacy branch of the build pack.  Thanks for you help,
